apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s
  name: k8s
  namespace: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
        namespace: helloworld
    spec:
      containers:
      - name: k8s
        image: torpedokim/helloworld:17
        ports:
          - containerPort: 8569